// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/prelude.proto

package proto

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on STPreludePingReq with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *STPreludePingReq) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Name

	return nil
}

// STPreludePingReqValidationError is the validation error returned by
// STPreludePingReq.Validate if the designated constraints aren't met.
type STPreludePingReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e STPreludePingReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e STPreludePingReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e STPreludePingReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e STPreludePingReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e STPreludePingReqValidationError) ErrorName() string { return "STPreludePingReqValidationError" }

// Error satisfies the builtin error interface
func (e STPreludePingReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSTPreludePingReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = STPreludePingReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = STPreludePingReqValidationError{}

// Validate checks the field values on STPreludePingRsp with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *STPreludePingRsp) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for TraceId

	// no validation rules for Message

	return nil
}

// STPreludePingRspValidationError is the validation error returned by
// STPreludePingRsp.Validate if the designated constraints aren't met.
type STPreludePingRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e STPreludePingRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e STPreludePingRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e STPreludePingRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e STPreludePingRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e STPreludePingRspValidationError) ErrorName() string { return "STPreludePingRspValidationError" }

// Error satisfies the builtin error interface
func (e STPreludePingRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSTPreludePingRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = STPreludePingRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = STPreludePingRspValidationError{}
