// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prelude.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 服务错误码
// 下列错误码会同步至commont/error/error.go文件中
type ErrCode int32

const (
	ErrCode_ErrOk          ErrCode = 0
	ErrCode_ErrUnknown     ErrCode = 101
	ErrCode_ErrArgsInvalid ErrCode = 102
	ErrCode_ErrArgsEmpty   ErrCode = 103
	ErrCode_ErrSystem      ErrCode = 104
	ErrCode_ErrDB          ErrCode = 105
	ErrCode_ErrNoServe     ErrCode = 106
)

var ErrCode_name = map[int32]string{
	0:   "ErrOk",
	101: "ErrUnknown",
	102: "ErrArgsInvalid",
	103: "ErrArgsEmpty",
	104: "ErrSystem",
	105: "ErrDB",
	106: "ErrNoServe",
}

var ErrCode_value = map[string]int32{
	"ErrOk":          0,
	"ErrUnknown":     101,
	"ErrArgsInvalid": 102,
	"ErrArgsEmpty":   103,
	"ErrSystem":      104,
	"ErrDB":          105,
	"ErrNoServe":     106,
}

func (x ErrCode) String() string {
	return proto.EnumName(ErrCode_name, int32(x))
}

func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ba16b4045264287a, []int{0}
}

// Ping请求
type STPreludePingReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *STPreludePingReq) Reset()         { *m = STPreludePingReq{} }
func (m *STPreludePingReq) String() string { return proto.CompactTextString(m) }
func (*STPreludePingReq) ProtoMessage()    {}
func (*STPreludePingReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba16b4045264287a, []int{0}
}

func (m *STPreludePingReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_STPreludePingReq.Unmarshal(m, b)
}
func (m *STPreludePingReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_STPreludePingReq.Marshal(b, m, deterministic)
}
func (m *STPreludePingReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_STPreludePingReq.Merge(m, src)
}
func (m *STPreludePingReq) XXX_Size() int {
	return xxx_messageInfo_STPreludePingReq.Size(m)
}
func (m *STPreludePingReq) XXX_DiscardUnknown() {
	xxx_messageInfo_STPreludePingReq.DiscardUnknown(m)
}

var xxx_messageInfo_STPreludePingReq proto.InternalMessageInfo

func (m *STPreludePingReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Ping响应
type STPreludePingRsp struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=traceId,proto3" json:"traceId"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *STPreludePingRsp) Reset()         { *m = STPreludePingRsp{} }
func (m *STPreludePingRsp) String() string { return proto.CompactTextString(m) }
func (*STPreludePingRsp) ProtoMessage()    {}
func (*STPreludePingRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba16b4045264287a, []int{1}
}

func (m *STPreludePingRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_STPreludePingRsp.Unmarshal(m, b)
}
func (m *STPreludePingRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_STPreludePingRsp.Marshal(b, m, deterministic)
}
func (m *STPreludePingRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_STPreludePingRsp.Merge(m, src)
}
func (m *STPreludePingRsp) XXX_Size() int {
	return xxx_messageInfo_STPreludePingRsp.Size(m)
}
func (m *STPreludePingRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_STPreludePingRsp.DiscardUnknown(m)
}

var xxx_messageInfo_STPreludePingRsp proto.InternalMessageInfo

func (m *STPreludePingRsp) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *STPreludePingRsp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("prelude.ErrCode", ErrCode_name, ErrCode_value)
	proto.RegisterType((*STPreludePingReq)(nil), "prelude.STPreludePingReq")
	proto.RegisterType((*STPreludePingRsp)(nil), "prelude.STPreludePingRsp")
}

func init() { proto.RegisterFile("prelude.proto", fileDescriptor_ba16b4045264287a) }

var fileDescriptor_ba16b4045264287a = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4e, 0x02, 0x31,
	0x18, 0x84, 0x85, 0xa0, 0x1b, 0x1a, 0xd8, 0x34, 0xd5, 0x03, 0x6e, 0x3c, 0x18, 0x0e, 0xc6, 0x18,
	0xd9, 0x05, 0x3c, 0x68, 0xbc, 0x81, 0xae, 0x09, 0x17, 0x25, 0xa0, 0x47, 0x0f, 0x95, 0xfd, 0xad,
	0x2b, 0x6c, 0x5b, 0xff, 0x56, 0x08, 0x31, 0x5e, 0x7c, 0x04, 0x7d, 0x34, 0x5f, 0xc1, 0x07, 0x31,
	0x2c, 0xe5, 0x82, 0xf1, 0xd4, 0x4e, 0xe7, 0xcb, 0x64, 0x3a, 0xa4, 0xaa, 0x11, 0x26, 0xaf, 0x09,
	0x84, 0x1a, 0x95, 0x55, 0xcc, 0x73, 0x32, 0xd8, 0x13, 0x4a, 0x89, 0x09, 0x44, 0x5c, 0xa7, 0x11,
	0x97, 0x52, 0x59, 0x6e, 0x53, 0x25, 0xcd, 0x12, 0x0b, 0x8e, 0xf3, 0x63, 0xd4, 0x10, 0x20, 0x1b,
	0x66, 0xc6, 0x85, 0x00, 0x8c, 0x94, 0xce, 0x89, 0xbf, 0x74, 0xfd, 0x80, 0xd0, 0xe1, 0x6d, 0x7f,
	0x19, 0xdc, 0x4f, 0xa5, 0x18, 0xc0, 0x0b, 0x63, 0xa4, 0x24, 0x79, 0x06, 0xb5, 0xc2, 0x7e, 0xe1,
	0xb0, 0x3c, 0xc8, 0xef, 0xf5, 0xab, 0x75, 0xce, 0x68, 0x56, 0x23, 0x9e, 0x45, 0x3e, 0x82, 0x5e,
	0xe2, 0xd0, 0x95, 0x5c, 0x38, 0x19, 0x18, 0xc3, 0x05, 0xd4, 0x8a, 0x4b, 0xc7, 0xc9, 0x23, 0x4b,
	0xbc, 0x18, 0xf1, 0x42, 0x25, 0xc0, 0xca, 0x64, 0x33, 0x46, 0xbc, 0x19, 0xd3, 0x0d, 0xe6, 0x13,
	0x12, 0x23, 0xde, 0xc9, 0xb1, 0x54, 0x33, 0x49, 0x81, 0x31, 0xe2, 0xc7, 0x88, 0x1d, 0x14, 0xa6,
	0x27, 0xa7, 0x7c, 0x92, 0x26, 0xf4, 0x91, 0x51, 0x52, 0x71, 0x6f, 0x71, 0xa6, 0xed, 0x9c, 0x0a,
	0x56, 0x25, 0xe5, 0x18, 0x71, 0x38, 0x37, 0x16, 0x32, 0xfa, 0xe4, 0xf2, 0x2e, 0xbb, 0x34, 0x75,
	0x79, 0xd7, 0x6a, 0x08, 0x38, 0x05, 0xfa, 0xdc, 0xbe, 0x27, 0x9e, 0xeb, 0xce, 0x06, 0xa4, 0xb4,
	0xe8, 0xcf, 0x76, 0xc3, 0xd5, 0xba, 0xeb, 0xff, 0x0f, 0xfe, 0xb3, 0x8c, 0xae, 0xef, 0x7c, 0x7c,
	0xff, 0x7c, 0x15, 0x7d, 0x56, 0x89, 0x74, 0x2a, 0x45, 0xf4, 0xb6, 0xd8, 0xe6, 0xbd, 0xbb, 0xfd,
	0xd9, 0xa1, 0x81, 0xdf, 0x6a, 0x9f, 0x86, 0xcd, 0xb0, 0x19, 0xb6, 0xce, 0xcf, 0xda, 0xcd, 0xd6,
	0xc3, 0x56, 0x3e, 0xf0, 0xc9, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x1b, 0x94, 0xdd, 0xc6,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PreludeClient is the client API for Prelude service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PreludeClient interface {
	//ping 服务check接口
	Ping(ctx context.Context, in *STPreludePingReq, opts ...grpc.CallOption) (*STPreludePingRsp, error)
}

type preludeClient struct {
	cc *grpc.ClientConn
}

func NewPreludeClient(cc *grpc.ClientConn) PreludeClient {
	return &preludeClient{cc}
}

func (c *preludeClient) Ping(ctx context.Context, in *STPreludePingReq, opts ...grpc.CallOption) (*STPreludePingRsp, error) {
	out := new(STPreludePingRsp)
	err := c.cc.Invoke(ctx, "/prelude.Prelude/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PreludeServer is the server API for Prelude service.
type PreludeServer interface {
	//ping 服务check接口
	Ping(context.Context, *STPreludePingReq) (*STPreludePingRsp, error)
}

// UnimplementedPreludeServer can be embedded to have forward compatible implementations.
type UnimplementedPreludeServer struct {
}

func (*UnimplementedPreludeServer) Ping(ctx context.Context, req *STPreludePingReq) (*STPreludePingRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterPreludeServer(s *grpc.Server, srv PreludeServer) {
	s.RegisterService(&_Prelude_serviceDesc, srv)
}

func _Prelude_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(STPreludePingReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PreludeServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prelude.Prelude/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PreludeServer).Ping(ctx, req.(*STPreludePingReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Prelude_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prelude.Prelude",
	HandlerType: (*PreludeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Prelude_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prelude.proto",
}
